name: Build and Release Runners

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'runner/**'
      - .github/workflows/build-and-release-runners.yml
  push:
    branches:
      - master
    paths:
      - runner/patched/*
      - runner/Dockerfile
      - runner/dindrunner.Dockerfile
      - runner/entrypoint.sh
      - .github/workflows/build-and-release-runners.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: actions-runner
            dockerfile: Dockerfile
          - name: actions-runner-dind
            dockerfile: dindrunner.Dockerfile
    env:
      RUNNER_VERSION: 2.277.1
      DOCKER_VERSION: 19.03.12
      DOCKER_QUAY_REGISTRY: quay.io
      DOCKER_QUAY_NAMESPACE: sundae
    steps:
      - name: Set Outputs
        id: vars
        run: echo ::set-output name=sha_short::${GITHUB_SHA::7}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1.1.1
        with:
          version: latest

      - name: Cache Docker Layers
        uses: actions/cache@2.1.4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Image and push to Quay
        uses: docker/build-push-action@v2
        id: docker-build
        with:
          context: ./runner
          file: ./runner/${{ matrix.dockerfile }}
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          push: true
          build-args: |
            RUNNER_VERSION=${{ env.RUNNER_VERSION }}
            DOCKER_VERSION=${{ env.DOCKER_VERSION }}
          tags: |
            ${{ matrix.name }}:v${{ env.RUNNER_VERSION }}
            ${{ matrix.name }}:v${{ env.RUNNER_VERSION }}-${{ steps.vars.outputs.sha_short }}
            ${{ matrix.name }}:latest
          registry: ${{ env.DOCKER_QUAY_REGISTRY }}
          repository: ${{ env.DOCKER_QUAY_NAMESPACE }}/${{ matrix.name }}
          username: ${{ secrets.DOCKER_QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.DOCKER_QUAY_ROBOT_PASSWORD }}
