name: Build and Release Runners

on:
  pull_request:
    branches:
      - 'master'
    types:
      - opened
      - closed
      - reopened
    paths:
      - 'runner/**'
      - .github/workflows/build-and-release-runners.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: actions-runner
            dockerfile: Dockerfile
          - name: actions-runner-dind
            dockerfile: dindrunner.Dockerfile
    env:
      RUNNER_VERSION: 2.277.1
      DOCKER_VERSION: 19.03.12
      DOCKER_QUAY_REGISTRY: quay.io
      DOCKER_QUAY_NAMESPACE: sundae
    steps:
      - name: Set Outputs
        id: vars
        run: echo ::set-output name=sha_short::${GITHUB_SHA::7}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1.1.1
        with:
          version: latest

      - name: Build ${{ matrix.name }} Image Locally
        uses: docker/build-push-action@v1
        if: github.event.pull_request.merged != true
        with:
          context: ./runner
          file: ./runner/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: false
          build-args: |
            RUNNER_VERSION=${{ env.RUNNER_VERSION }}
            DOCKER_VERSION=${{ env.DOCKER_VERSION }}
          tags: v${{ env.RUNNER_VERSION }}, v${{ env.RUNNER_VERSION }}-${{ steps.vars.outputs.sha_short }}, latest

      - name: Test Local ${{ matrix.name }} Image
        id: image-test
        run: echo ::set-output name=image_status::$(docker run ${{ matrix.name }}:latest)

      - name: TEST - show output of previous step
        run: echo ${{ steps.image-test.outputs.image_status }}

      - name: Build ${{ matrix.name }} Image and push to Quay
        uses: docker/build-push-action@v1
        if: github.event.pull_request.merged == true
        with:
          context: ./runner
          file: ./runner/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            RUNNER_VERSION=${{ env.RUNNER_VERSION }}
            DOCKER_VERSION=${{ env.DOCKER_VERSION }}
          tags: v${{ env.RUNNER_VERSION }}, v${{ env.RUNNER_VERSION }}-${{ steps.vars.outputs.sha_short }}, latest
          registry: ${{ env.DOCKER_QUAY_REGISTRY }}
          repository: ${{ env.DOCKER_QUAY_NAMESPACE }}/${{ matrix.name }}
          username: ${{ secrets.DOCKER_QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.DOCKER_QUAY_ROBOT_PASSWORD }}
