name: Build and Release Runners

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'runner/**'
      - .github/workflows/build-and-release-runners.yml
  push:
    branches:
      - master
    paths:
      - runner/patched/*
      - runner/Dockerfile
      - runner/dindrunner.Dockerfile
      - runner/entrypoint.sh
      - .github/workflows/build-and-release-runners.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: actions-runner
            dockerfile: Dockerfile
          - name: actions-runner-dind
            dockerfile: dindrunner.Dockerfile
    env:
      RUNNER_VERSION: 2.277.1
      DOCKER_VERSION: 19.03.12
      DOCKER_QUAY_REPO: quay.io/sundae/actions-runner
      DOCKER_QUAY_NAMESPACE: sundae
    steps:
      - name: Set Outputs
        id: vars
        run: echo ::set-output name=sha_short::${GITHUB_SHA::7}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1.1.1
        with:
          version: latest
          install: true

      - name: Login to Quay
        run: |
          echo "${{ secrets.DOCKER_QUAY_ROBOT_PASSWORD}}" | docker login quay.io -u "${{ secrets.DOCKER_QUAY_ROBOT_USERNAME}}" --password-stdin

      - name: Build Image
        uses: docker/build-push-action@v2.3.0
        id: docker-build
        with:
          context: ./runner
          file: ./runner/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: false
          build-args: |
            RUNNER_VERSION=${{ env.RUNNER_VERSION }}
            DOCKER_VERSION=${{ env.DOCKER_VERSION }}
          tags: |
            ${{ matrix.name }}:v${{ env.RUNNER_VERSION }}
            ${{ matrix.name }}:v${{ env.RUNNER_VERSION }}-${{ steps.vars.outputs.sha_short }}
            ${{ matrix.name }}:latest

      # - name: Build Image
      #   uses: redhat-actions/buildah-build@v2.3
      #   id: docker-build
      #   with:
      #     archs: amd64, arm64
      #     context: ./runner
      #     dockerfiles: ./runner/${{ matrix.dockerfile }}
      #     build-args: |
      #       RUNNER_VERSION=${{ env.RUNNER_VERSION }}
      #       DOCKER_VERSION=${{ env.DOCKER_VERSION }}
      #       TARGETPLATFORM=linux
      #     image: ${{ matrix.name }}
      #     oci: true
      #     tags: v${{ env.RUNNER_VERSION }} v${{ env.RUNNER_VERSION }}-${{ steps.vars.outputs.sha_short }} latest

      - name: Push to Quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ matrix.name }}
          tags: latest v${{ env.RUNNER_VERSION }}-${{ steps.vars.outputs.sha_short }} v${{ env.RUNNER_VERSION }}
          registry: ${{ env.DOCKER_QUAY_REPO }}
          username: ${{ secrets.DOCKER_QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.DOCKER_QUAY_ROBOT_PASSWORD }}
